# Generated by Django 3.0.7 on 2020-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('real_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('url', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['-real_rate', 'name'],
            },
        ),
    ]
