# Generated by Django 3.1.2 on 2021-01-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
